name = "juicypleasure-worker"
main = "worker.js"
compatibility_date = "2024-08-01"

# ✅ CRITICAL ADDITIONS:
compatibility_flags = ["nodejs_compat"]
usage_model = "bundled"
logpush = true

[vars]
ENVIRONMENT = "production"
PIXEL_ID = "1091970342909970"

[[triggers]]
workers_dev = true

[deployment]
env = "production"
branch = "main"

[logpush]
enabled = true

[tail]
enabled = true
